version : 0.2

phases:
 	pre_build : 
 		commands :
 			- echo "Entered Pre Build Phase"
 	build :
 		commands :
 		 	- echo "Entered Build Phase"
 		 	- mvn clean pre-package war:exploded
 	post_build :
 		commands :
 			- echo "Entered Post Build Phase"
 			- mv targe/deploy
 	artifacts
 		files :
 			- deploy/**/* 